# Generated by Django 3.2.13 on 2022-07-12 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='Delish1/images')),
                ('veg', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('payment_mode', models.CharField(default='COD', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date(2007, 7, 27))),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_MENU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='notGiven', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delish1.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delish1.order')),
            ],
            options={
                'unique_together': {('order', 'menu_item')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(through='Delish1.ORDER_MENU', to='Delish1.MENU'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
