# Generated by Django 3.2.13 on 2022-07-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
