# Generated by Django 3.2.8 on 2021-11-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
