# Generated by Django 3.2.8 on 2021-11-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
