# Generated by Django 3.2.8 on 2021-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0004_auto_20211114_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
