# Generated by Django 3.2.8 on 2021-11-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
