# Generated by Django 3.2.8 on 2021-11-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0007_auto_20211115_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='Delish/images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
