# Generated by Django 3.2.8 on 2021-11-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0008_auto_20211115_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to='Delish1/images'),
        ),
    ]
