# Generated by Django 3.2.8 on 2021-11-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0010_order_menu_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_str',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
