# Generated by Django 3.2.13 on 2022-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delish1', '0012_auto_20211116_0435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
        migrations.AddField(
            model_name='menu',
            name='veg',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='order_menu',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
